# 概念

## 1、关联规则
    关联规则是反应一个事物与其他事物之间的相互依存性，如果两个或者多个事物之间存在一定的关联关系，那么其中一个事物就可以通过其他事物预测到。
    关联规则挖掘的最经典的例子就是沃尔玛的啤酒与尿布的故事，通过对超市购物篮数据进行分析，即顾客放入购物篮中不同商品之间的关系来分析顾客的购物习惯，发现美国妇女们经常会叮嘱丈夫下班后为孩子买尿布，30%-40%的丈夫同时会顺便购买喜爱的啤酒，超市就把尿布和啤酒放在一起销售增加销售额。有了这个发现后，超市调整了货架的设置，把尿布和啤酒摆放在一起销售，从而大大增加了销售额。
    相关案例有：
        (1) 沃尔玛超市的尿布与啤酒
        (2) 超市的牛奶与面包
        (3) 百度文库推荐相关文档
        (4) 淘宝推荐相关书籍
        (5) 医疗推荐可能的治疗组合
        (6) 银行推荐相关联业务
    （1）、项集：
        项集是项的集合。 包含k个项的项集称为k项集， 如集合{牛奶， 麦片， 糖}         是一个3项集。
    （2）支持度：
          项集A、 B同时发生的概率称为关联规则的支持度，也就是交易集中同时包  含A和B的交易数与所有交易数之比。
          Support(A=>B)=P(A并B)=count(A并B)/|D|
    （3）置信度：项集A发生， 则项集B发生的概率为关联规则的置信度。也就是说包含A和B交易次数与包含A的交易数之比。
          Confidence(A=>B)=P(B|A)=support(A并B)/support(A)
    （4）最小支持度与频繁集
        发现关联规则要求项集必须满足的最小支持阈值，称为项集的最小支持度（Minimum Support），记为supmin。支持度大于或等于supmin的项集称为频繁项集，简称频繁集，反之则称为非频繁集。通常k-项集如果满足supmin，称为k-频繁集，记作Lk。关联规则的最小置信度（Minimum Confidence）记为confmin，它表示关联规则需要满足的最低可靠性。
    （5）、定义：关联规则可以表示为一个蕴含式：R:X=》Y
    例如：R：尿布->啤酒
    （6）、强关联关系：如果规则R：X=>Y 满足 support(X=>Y) >= supmin（最小支持度） 且 confidence(X=>Y)>=confmin（最小置信度），称关联规则X=>Y为强关联规则，否则称关联规则X=>Y为弱关联规则。

## Apriori算法挖掘频繁项集
    （1）关联规则对购物篮进行挖掘，通常采用两个步骤进行：
        a.找出所有频繁项集（文章中我使用Apriori算法>=最小支持度的项集）
        b.由频繁项集产生强关联规则，这些规则必须大于或者等于最小支持度和最小置信度。
        
    （2）下面将通超市购物的例子对关联规则挖掘Apriori算法进行分析。
        Apriori算法是一种对有影响的挖掘布尔关联规则频繁项集的算法，通过算法的连接和剪枝即可挖掘频繁项集。
        
    （3）Apriori算法将发现关联规则的过程分为两个步骤：
        1.通过迭代，检索出事务数据库中的所有频繁项集，即支持度不低于用户设定的阈值的项集；
        2.利用频繁项集构造出满足用户最小置信度的规则。
        挖掘或识别出所有频繁项集是该算法的核心，占整个计算量的大部分。
    （4）Apriori算法的重要性质：
        1、频繁项集的子集必为频繁项集。假设{A,C}是频繁项集，则{A}和{C}也是频繁项集。
        2、非频繁项集的超级一定是非频繁的，假设项集{D}是非频繁的，这{A,D}，{C,D}也是非频繁项集。

## Apriori算法的思路
    （1）由频繁(k-1)-项集生成候选k-项集，然后根据最小支持度判断该候选k-项集是否是频繁k-项集。 
    例如先找出所有1-项集，然后筛选出里面的频繁1-项集； 根据频繁1-项集生成候选2-项集，然后筛选出里面的频繁2-项集； 再根据频繁2-项集生成候选3-项集，从里面筛选出频繁3-项集；·······
    （2）如何从频繁(k-1)-项集生成候选k-项集呢？
        利用Apriori性质：一个频繁项集的任一子集也应该是频繁子集（用反证法容易证明，略）。所以如果一个项集是非频繁项集，那么它的超集也应该是非频繁项集。 
    （3）从频繁1-项集生成候选2-项集的步骤是：把频繁1-项集和频繁1-项集排列组合成2-项集，把含有非频繁子项集的2-项集去掉，就是候选2-项集了。从频繁2-项集生成候选三项集的步骤是：把频繁2-项集和频繁1-项集排列组合成3-项集。
    
    举例(最小支持度为2)：
       id    Items
       10    A,C,D
       20    B,C,D
       30    A,B,C,D
       40    B,E
    1、得到频繁1-项集： 
     (1)  Itemset    sup 
           {A}        2
           {B}        3
           {C}        3
           {D}        1
           {E}        3

     (2)   Itemset    sup 
           {A}        2
           {B}        3
           {C}        3
           {E}        3
    2、得到频繁2-项集： 
     (1)   Itemset   
           {A,B}     
           {A,C}      
           {A,E}     
           {B,C}     
           {B,E}      
           {C,E}    

     (2)   Itemset    sup 
           {A,B}        1
           {A,C}        2
           {A,E}        1
           {B,C}        2
           {B,E}        3
           {C,E}        2

     (3)   Itemset    sup 
           {A,C}        2
           {B,C}        2
           {B,E}        3
           {C,E}        2
    3、得到频繁3-项集：
     (1)   Itemset
           {B,C,E}

     (2)   Itemset    sup 
           {B,C,E}     2
    具体分析结果：
            第一次扫描：对每个候选商品计数得C1，由于候选{D}支持度计数为1<最小支持度计数2，故删除{D}得频繁1-项集合L1；
            第二次扫描：由L1产生候选C2并对候选计数得C2，比较候选支持度计数与最小支持度计数2得频繁2-项集合L2；
            第三次扫描：用Apriori算法对L2进行连接和剪枝产生候选3项集合C3的过程如下：
            1.连接：
            C3=L2\bowtie(连接)L2={{A,C},{B,C},{B,E},{C,E}}\bowtie{{A,C},{B,C},{B,E},{C,E}}={{A,B,C},{A,C,E},{B,C,E}}
            2.剪枝：
            {A,B,C}的2项子集{A,B},{A,C}和{B,C}，其中{A,B}不是2项子集L2，因此不是频繁的，从C3中删除；
            {A,C,E}的2项子集{A,C},{A,E}和{C,E}，其中{A,E}不是2项子集L2，因此不是频繁的，从C3中删除；
            {B,C,E}的2项子集{B,C},{B,E}和{C,E}，它的所有2项子集都是L2的元素，保留C3中。
            经过Apriori算法对L2连接和剪枝后产生候选3项集的集合为C3={B,C,E}. 在对该候选商品计数，由于等于最小支持度计数2，故得频繁3-项集合L3，同时由于4-项集中仅1个，故C4为空集，算法终止。

##   Apriori算法弊端：
    Apriori算法是通过频繁(k-1)-项集找到频繁k-项集的，虽然可以通过Apriori性质进行减枝，去掉一部分子集为非频繁项集的候选项集，但还是需要多次扫描数据表。如果频繁集最多包含10个项，那么就需要扫描交易数据表10遍，这需要很大的I/O负载。同时，产生大量频繁集。所以，不断地求候选项集的支持度计数从而判断它是否是频繁项集。如果数据集足够大的时候，这种算法的效率还是挺让人捉急的！
    
    参考：
    http://blog.csdn.net/eastmount/article/details/53368440
    http://blog.csdn.net/bone_ace/article/details/46660819

## 代码

In [2]:
#-*- coding: utf-8 -*-
from __future__ import print_function
import pandas as pd

#自定义连接函数，用于实现L_{k-1}到C_k的连接
def connect_string(x, ms):
    x = list(map(lambda i:sorted(i.split(ms)), x))
    l = len(x[0])
    r = []
    for i in range(len(x)):
        for j in range(i,len(x)):
            if x[i][:l-1] == x[j][:l-1] and x[i][l-1] != x[j][l-1]:
                r.append(x[i][:l-1]+sorted([x[j][l-1],x[i][l-1]]))
    return r

#寻找关联规则的函数
def find_rule(d, support, confidence, ms = u'--'):
    result = pd.DataFrame(index=['support', 'confidence']) #定义输出结果

    support_series = 1.0*d.sum()/len(d) #支持度序列
    column = list(support_series[support_series > support].index) #初步根据支持度筛选
    k = 0
  
    while len(column) > 1:
        k = k+1
        print(u'\n正在进行第%s次搜索...' %k)
        column = connect_string(column, ms)
        print(u'数目：%s...' %len(column))
        sf = lambda i: d[i].prod(axis=1, numeric_only = True) #新一批支持度的计算函数

        #创建连接数据，这一步耗时、耗内存最严重。当数据集较大时，可以考虑并行运算优化。
        d_2 = pd.DataFrame(list(map(sf,column)), index = [ms.join(i) for i in column]).T

        support_series_2 = 1.0*d_2[[ms.join(i) for i in column]].sum()/len(d) #计算连接后的支持度
        column = list(support_series_2[support_series_2 > support].index) #新一轮支持度筛选
        support_series = support_series.append(support_series_2)
        column2 = []

        for i in column: #遍历可能的推理，如{A,B,C}究竟是A+B-->C还是B+C-->A还是C+A-->B？
            i = i.split(ms)
            for j in range(len(i)):
                column2.append(i[:j]+i[j+1:]+i[j:j+1])
    
        cofidence_series = pd.Series(index=[ms.join(i) for i in column2]) #定义置信度序列
 
        for i in column2: #计算置信度序列
            cofidence_series[ms.join(i)] = support_series[ms.join(sorted(i))]/support_series[ms.join(i[:len(i)-1])]
    
        for i in cofidence_series[cofidence_series > confidence].index: #置信度筛选
            result[i] = 0.0
            result[i]['confidence'] = cofidence_series[i]
            result[i]['support'] = support_series[ms.join(sorted(i.split(ms)))]
  
    result = result.T.sort(['confidence','support'], ascending = False) #结果整理，输出
    print(u'\n结果为：')
    print(result)
  
    return result

### Apriori算法挖掘菜品订单关联规则

In [3]:
import pandas as pd
input_file='E://learnFile//chapter5//demo//data/menu_orders.xls'
data=pd.read_excel(input_file)
data.head()

   a  c    e Unnamed: 3
0  b  d  NaN        NaN
1  b  c  NaN        NaN
2  a  b    c          d
3  a  b  NaN        NaN
4  b  c  NaN        NaN

In [4]:
data=pd.read_excel(input_file,header=None)
data.head()

   0  1    2    3
0  a  c    e  NaN
1  b  d  NaN  NaN
2  b  c  NaN  NaN
3  a  b    c    d
4  a  b  NaN  NaN

In [5]:
print("转换原始数据至0-1矩阵")
ct=lambda x:pd.Series(1,index=x[pd.notnull(x)])

转换原始数据至0-1矩阵

In [6]:
b=map(ct,data.as_matrix())
data1=pd.DataFrame(list(b)).fillna(0)

In [7]:
data1

     a    b    c    d    e
0  1.0  0.0  1.0  0.0  1.0
1  0.0  1.0  0.0  1.0  0.0
2  0.0  1.0  1.0  0.0  0.0
3  1.0  1.0  1.0  1.0  0.0
4  1.0  1.0  0.0  0.0  0.0
5  0.0  1.0  1.0  0.0  0.0
6  1.0  1.0  0.0  0.0  0.0
7  1.0  1.0  1.0  0.0  1.0
8  1.0  1.0  1.0  0.0  0.0
9  1.0  0.0  1.0  0.0  1.0

In [8]:
s=0.2
c=0.5
ms='---'
result=find_rule(data1,s,c,ms)

正在进行第1次搜索...
数目：6...

正在进行第2次搜索...
数目：3...

正在进行第3次搜索...
数目：0...

结果为：
           support  confidence
e---a          0.3    1.000000
e---c          0.3    1.000000
c---e---a      0.3    1.000000
a---e---c      0.3    1.000000
a---b          0.5    0.714286
c---a          0.5    0.714286
a---c          0.5    0.714286
c---b          0.5    0.714286
b---a          0.5    0.625000
b---c          0.5    0.625000
b---c---a      0.3    0.600000
a---c---b      0.3    0.600000
a---b---c      0.3    0.600000
a---c---e      0.3    0.600000

C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:54: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [9]:
result

           support  confidence
e---a          0.3    1.000000
e---c          0.3    1.000000
c---e---a      0.3    1.000000
a---e---c      0.3    1.000000
a---b          0.5    0.714286
c---a          0.5    0.714286
a---c          0.5    0.714286
c---b          0.5    0.714286
b---a          0.5    0.625000
b---c          0.5    0.625000
b---c---a      0.3    0.600000
a---c---b      0.3    0.600000
a---b---c      0.3    0.600000
a---c---e      0.3    0.600000

## 中医证型关联规则挖掘

## 数据聚类离散化

In [10]:
import pandas as pd
from sklearn.cluster import KMeans
input_file='E://learnFile//chapter8//demo/data/data.xls'
data=pd.read_excel(input_file)
data.head()

,肝气郁结证型系数,热毒蕴结证型系数,冲任失调证型系数,气血两虚证型系数,脾胃虚弱证型系数,肝肾阴虚证型系数,病程阶段,TNM分期,转移部位,确诊后几年发现转移
0,0.056,0.460,0.281,0.352,0.119,0.350,S4,H4,R1,J1
1,0.488,0.099,0.283,0.333,0.116,0.293,S4,H4,R1,J1
2,0.107,0.008,0.204,0.150,0.032,0.159,S4,H4,R2,J2
3,0.322,0.208,0.305,0.130,0.184,0.317,S4,H4,R2,J1
4,0.242,0.280,0.131,0.210,0.191,0.351,S4,H4,R2R5,J1

In [13]:
k=4#j聚类类别数
typelabel ={u'肝气郁结证型系数':'A', u'热毒蕴结证型系数':'B', u'冲任失调证型系数':'C', u'气血两虚证型系数':'D', u'脾胃虚弱证型系数':'E', u'肝肾阴虚证型系数':'F'}
keys=list(typelabel.keys())

In [18]:
result=pd.DataFrame()
if __name__=='__main__':
    for i in range(len(keys)):
        kmodel=KMeans(n_clusters=k,n_jobs=4)
        kmodel.fit(data[[keys[i]]].as_matrix())
        r1=pd.DataFrame(kmodel.cluster_centers_,columns=[typelabel[keys[i]]])
        r2=pd.Series(kmodel.labels_).value_counts()
        r2=pd.DataFrame(r2,columns=[typelabel[keys[i]]+'n'])#记录各个类别的数目
        r=pd.concat([r1,r2],axis=1).sort(typelabel[keys[i]])
        
        r.index=[1,2,3,4]
        
        #计算相邻2列的均值，作为边界点
        r[typelabel[keys[i]]]=pd.rolling_mean(r[typelabel[keys[i]]],2)
        r[typelabel[keys[i]]][1]=0.0#两句代码将原来的聚类中心改为边界点
        
        result=result.append(r.T)
    result=result.sort()

C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:14: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=2,center=False).mean()
C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:18: FutureWarning: sort(....) is deprecated, use sort_index(.....)

In [19]:
result

        1           2           3           4
A     0.0    0.178698    0.257724    0.351843
An  240.0  356.000000  281.000000   53.000000
B     0.0    0.154031    0.306200    0.564697
Bn  342.0  384.000000  194.000000   10.000000
C     0.0    0.202149    0.289061    0.423537
Cn  297.0  394.000000  204.000000   35.000000
D     0.0    0.172281    0.251683    0.359353
Dn  283.0  375.000000  228.000000   44.000000
E     0.0    0.152698    0.257873    0.376062
En  273.0  319.000000  245.000000   93.000000
F     0.0    0.179143    0.261386    0.354643
Fn  200.0  237.000000  265.000000  228.000000

##  Apriori关联规则代码

In [20]:
import pandas as pd
import time
input_file='E://learnFile//chapter8//demo/data/apriori.txt'
data=pd.read_csv(input_file,header=None,dtype=object)
data.head()

    0   1   2   3   4   5   6
0  A2  B1  C3  D3  E1  F1  H1
1  A2  B1  C3  D3  E1  F1  H1
2  A2  B1  C3  D3  E1  F1  H1
3  A2  B1  C3  D3  E1  F1  H1
4  A2  B2  C3  D3  E1  F1  H1

In [21]:
start=time.clock()
print("转换原始数据至0-1矩阵")
ct=lambda x:pd.Series(1,index=x[pd.notnull(x)])
b=map(ct,data.as_matrix())
data1=pd.DataFrame(list(b)).fillna(0)
end=time.clock()

转换原始数据至0-1矩阵

In [25]:
data1.head()

,A1,A2,A3,A4,B1,B2,B3,B4,C1,C2,...,E3,E4,F1,F2,F3,F4,H1,H2,H3,H4
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [28]:
s=0.06
c=0.75
ms='---'
start = time.clock() #计时开始
print(u'\n开始搜索关联规则...')
result=find_rule(data1, s, c, ms)
end = time.clock() #计时结束
print(u'\n搜索完成， 用时：%0.2f秒' %(end-start))

开始搜索关联规则...

正在进行第1次搜索...
数目：276...

正在进行第2次搜索...
数目：947...

正在进行第3次搜索...
数目：41...

结果为：
                    support  confidence
A3---F4---H4       0.078495    0.879518
C3---F4---H4       0.075269    0.875000
B2---F4---H4       0.062366    0.794521
C2---E3---D2       0.092473    0.754386
D2---F3---H4---A2  0.062366    0.753247

搜索完成， 用时：1.74秒

C:\Users\pujing\Anaconda3\lib\site-packages\ipykernel\__main__.py:54: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)